update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :production do
    gradle(task: "clean bundleGplayRelease")
    upload_to_play_store(release_status: 'draft')
  end
end
