default_platform(:android)

platform :android do
  desc "Deploy to Google Play"
  lane :production do
    gradle(
      task: "clean bundleGplayRelease",
      project_dir: "..",
      gradle_path: "./gradlew"
    )
    upload_to_play_store(release_status: 'draft')
  end
end
